<?php

/*
 *  LOGIN.PHP
 *
 *  Allows a user to log in. Just displays a link with the login url 
 *  generated by fb/auth.php
 *
 */

require_once 'fb/auth.php';

// Redirect to index.php if the user is already logged in
if($user)
	header("Location: index.php");

?>

<!DOCTYPE html>
<html lang="en">
<head>
	<link rel="stylesheet" type="text/css" href="assets/bootstrap.min.css" />
</head>
<body>
	<div class='container' style='margin-top: 20px'>
		<div class='page-header'>
			<h1>Log in</h1>
		</div>
	</div>
</body>
</html>
